# 1. List[]

In [32]:
#1.Count how many customers are 31 years old.
customer_ages = [25, 31, 22, 31, 40,28, 22, 35, 31, 27]
customer_ages.count(31)

3

In [34]:
#2. Add a new customer aged 29
customer_ages = [25, 31, 22, 31, 40,28, 22, 35, 31, 27]
customer_ages.append(29)
customer_ages

[25, 31, 22, 31, 40, 28, 22, 35, 31, 27, 29]

In [12]:
#Add 2 new customers aged 35
customer_ages = [25, 31, 22, 31, 40,28, 22, 35, 31, 27]
customer_ages.insert(1,35)
customer_ages

[25, 35, 31, 22, 31, 40, 28, 22, 35, 31, 27]

In [8]:
#3. Add 2 new customers aged 21,23 from set ages
customer_ages = [25, 31, 22, 31, 40,28, 22, 35, 31, 27]
ages ={21,23}
customer_ages.extend(ages)
customer_ages

[25, 31, 22, 31, 40, 28, 22, 35, 31, 27, 21, 23]

In [14]:
#4. Remove one customer aged 22.
customer_ages = [25, 31, 22, 31, 40,28, 22, 35, 31, 27]
customer_ages.remove(22)
customer_ages

[25, 31, 31, 40, 28, 22, 35, 31, 27]

In [15]:
#5. Sort the ages
customer_ages = [25, 31, 22, 31, 40,28, 22, 35, 31, 27]
customer_ages.sort()
customer_ages

[22, 22, 25, 27, 28, 31, 31, 31, 35, 40]

In [17]:
#6. Reverse the sorted list.
customer_ages = [25, 31, 22, 31, 40,28, 22, 35, 31, 27]
customer_ages.sort(reverse=True)
customer_ages

[40, 35, 31, 31, 31, 28, 27, 25, 22, 22]

In [19]:
#7. Find the index of age 40
customer_ages = [25, 31, 22, 31, 40,28, 22, 35, 31, 27]
customer_ages.index(40)

4

In [21]:
#8. Copy the list
customer_ages = [25, 31, 22, 31, 40,28, 22, 35, 31, 27]
copied_customer_ages = customer_ages.copy()
copied_customer_ages

[25, 31, 22, 31, 40, 28, 22, 35, 31, 27]

In [22]:
#9. Clear the copied list.
customer_ages = [25, 31, 22, 31, 40,28, 22, 35, 31, 27]
copied_customer_ages = [25, 31, 22, 31, 40,28, 22, 35, 31, 27]
copied_customer_ages.clear()
copied_customer_ages

[]

In [27]:
#10 Print the maximum, minimum, sum, and average age
customer_ages = [25, 31, 22, 31, 40,28, 22, 35, 31, 27]
print(min(customer_ages))
print(max(customer_ages))
print(sum(customer_ages))
average_age = sum(customer_ages)/len(customer_ages)
print((average_age))

22
40
292
29.2

# 2.Set{}

In [1]:
#1. Add "Pineapple" to the set.
fruits = {"Apple", "Banana", "Orange", "Mango", "Grapes"}
fruits.add("Pineapple")
fruits

{'Apple', 'Banana', 'Grapes', 'Mango', 'Orange', 'Pineapple'}

In [18]:
fruits = {"Apple", "Banana", "Orange", "Mango", "Grapes"}
fruits.update(["Pineapple","Cherry"])
fruits

{'Apple', 'Banana', 'Cherry', 'Grapes', 'Mango', 'Orange', 'Pineapple'}

In [19]:
fruits = {"Apple", "Banana", "Orange", "Mango", "Grapes"}
fruits.pop()

'Grapes'

In [2]:
#2. Remove "Mango"
fruits = {"Apple", "Banana", "Orange", "Mango", "Grapes"}
fruits.remove("Mango")
fruits

{'Apple', 'Banana', 'Grapes', 'Orange'}

In [4]:
#3. Remove "Watermelon"
fruits = {"Apple", "Banana", "Orange", "Mango", "Grapes"}
fruits.discard("Watermelon")
fruits.remove("Watermelon")
fruits

KeyError: 'Watermelon'

In [7]:
#4. Print the number of fruits.
fruits = {"Apple", "Banana", "Orange", "Mango", "Grapes"}
len(fruits)

5

In [12]:
# all unique employee IDs
team_A = {"emp_101", "emp_102", "emp_103", "emp_104", "emp_105"}
team_B = {"emp_104", "emp_105", "emp_106", "emp_107", "emp_108"}
team_C = team_A.symmetric_difference(team_B)
team_C

{'emp_101', 'emp_102', 'emp_103', 'emp_106', 'emp_107', 'emp_108'}

In [22]:
# employees working only in team A
team_A = {"emp_101", "emp_102", "emp_103", "emp_104", "emp_105"}
team_B = {"emp_104", "emp_105", "emp_106", "emp_107", "emp_108"}
team_C = team_A.difference(team_B)
team_C

{'emp_101', 'emp_102', 'emp_103'}

In [14]:
#employees working in both teams
team_A = {"emp_101", "emp_102", "emp_103", "emp_104", "emp_105"}
team_B = {"emp_104", "emp_105", "emp_106", "emp_107", "emp_108"}
team_C = team_A.intersection(team_B)
team_C

{'emp_104', 'emp_105'}

In [15]:
# employees only in Team A
team_A = {"emp_101", "emp_102", "emp_103", "emp_104", "emp_105"}
team_B = {"emp_104", "emp_105", "emp_106", "emp_107", "emp_108"}
team_A

{'emp_101', 'emp_102', 'emp_103', 'emp_104', 'emp_105'}

In [17]:
# all employess in both the team.
team_A = {"emp_101", "emp_102", "emp_103", "emp_104", "emp_105"}
team_B = {"emp_104", "emp_105", "emp_106", "emp_107", "emp_108"}
team_C = team_A.union(team_B)
team_C

{'emp_101',
 'emp_102',
 'emp_103',
 'emp_104',
 'emp_105',
 'emp_106',
 'emp_107',
 'emp_108'}

In [24]:
team_A = {"emp_101", "emp_102", "emp_103", "emp_104", "emp_105"}
team_B = {"emp_104", "emp_105", "emp_106", "emp_107", "emp_108"}
team_A.issubset(team_B)

False

In [27]:
team_A = {"emp_104", "emp_105"}
team_B = {"emp_104", "emp_105", "emp_106", "emp_107", "emp_108"}
team_A.issubset(team_B)

True

In [28]:
team_A = {"emp_104", "emp_105"}
team_B = {"emp_104", "emp_105", "emp_106", "emp_107", "emp_108"}
team_A.issuperset(team_B)

False

In [31]:
team_A = {"emp_104", "emp_105"}
team_B = {"emp_104", "emp_105", "emp_106", "emp_107", "emp_108"}
team_A.isdisjoint(team_B)

False

# 3. Tuple ()

In [28]:
# how many times 5 appears.
ratings = (5, 4, 5, 3, 5, 2, 4, 5, 1)
ratings.count(5)

4

In [35]:
ratings = (5, 4, 5, 3, 5, 2, 4, 5, 1)
ratings.index(4)

1

In [36]:
ratings = (5, 4, 5, 3, 5, 2, 4, 5, 1)
ratings[4]

5

In [37]:
ratings = (5, 4, 5, 3, 5, 2, 4, 5, 1)
ratings[1:6]

(4, 5, 3, 5, 2)

# Dictionaries

In [45]:
#1 Create Data Frames
import pandas as pd
order_details = {"order_id":[101,102,103,104],
                 "customer_name" :["Maya","Jeni","Ajay","Vikram"]}
order_dataframe = pd.DataFrame(order_details)
order_dataframe

   order_id customer_name
0       101          Maya
1       102          Jeni
2       103          Ajay
3       104        Vikram

In [47]:
#2 Create Data Frames
import pandas as pd
category = { "product_name" : ["Table","Washing Machine","Television"],
             "product_category" : ["Furniture","Appliance","Electronic"]}

category_dataframe = pd.DataFrame(category)
category_dataframe

      product_name product_category
0            Table        Furniture
1  Washing Machine        Appliance
2       Television       Electronic

In [59]:
#3 Create Data Frames
import pandas as pd
employee = {
    "emp_id": [101,102],
    "name": ["Rahul","Ravi"],
    "skills": ["Python", "SQL"],
    "experience": [3,4],
    "city": ["Chennai","Bangalore"]}
employee_dataframe = pd.DataFrame(employee)
employee_dataframe

   emp_id   name  skills  experience       city
0     101  Rahul  Python           3    Chennai
1     102   Ravi     SQL           4  Bangalore

# 4 Dictionary functions

In [60]:
employee = {
    "emp_id": [101,102],
    "name": ["Rahul","Ravi"],
    "skills": ["Python", "SQL", "Excel"],
    "experience": [3,4],
    "city": ["Chennai","Bangalore"]}
employee["skills"]

['Python', 'SQL', 'Excel']

In [61]:
employee = {
    "emp_id": [101,102],
    "name": ["Rahul","Ravi"],
    "skills": ["Python", "SQL", "Excel"],
    "experience": [3,4],
    "city": ["Chennai","Bangalore"]}
employee.keys()

dict_keys(['emp_id', 'name', 'skills', 'experience', 'city'])

In [62]:
employee = {
    "emp_id": [101,102],
    "name": ["Rahul","Ravi"],
    "skills": ["Python", "SQL", "Excel"],
    "experience": [3,4],
    "city": ["Chennai","Bangalore"]}
employee.values()

dict_values([[101, 102], ['Rahul', 'Ravi'], ['Python', 'SQL', 'Excel'], [3, 4], ['Chennai', 'Bangalore']])

In [70]:
employee = {
    "emp_id": [101,102],
    "name": ["Rahul","Ravi"],
    "skills": ["Python", "SQL", "Excel"],
    "experience": [3,4],
    "city": ["Chennai","Bangalore"]}
employee.update({"skills":"python"})
employee

{'emp_id': [101, 102],
 'name': ['Rahul', 'Ravi'],
 'skills': 'python',
 'experience': [3, 4],
 'city': ['Chennai', 'Bangalore']}

In [68]:
employee = {
    "emp_id": [101,102],
    "name": ["Rahul","Ravi"],
    "skills": ["Python", "SQL", "Excel"],
    "experience": [3,4],
    "city": ["Chennai","Bangalore"]}
employee.items()

dict_items([('emp_id', [101, 102]), ('name', ['Rahul', 'Ravi']), ('skills', ['Python', 'SQL', 'Excel']), ('experience', [3, 4]), ('city', ['Chennai', 'Bangalore'])])

In [73]:
employee = {
    "emp_id": [101,102],
    "name": ["Rahul","Ravi"],
    "skills": ["Python", "SQL", "Excel"],
    "experience": [3,4],
    "city": ["Chennai","Bangalore"]}
employee.get("city")

['Chennai', 'Bangalore']

In [75]:
employee = {
    "emp_id": [101,102],
    "name": ["Rahul","Ravi"],
    "skills": ["Python", "SQL", "Excel"],
    "experience": [3,4],
    "city": ["Chennai","Bangalore"]}
employee.pop("city")
employee

{'emp_id': [101, 102],
 'name': ['Rahul', 'Ravi'],
 'skills': ['Python', 'SQL', 'Excel'],
 'experience': [3, 4]}

In [77]:
employees_team_A = {
    "emp_id": [101,102],
    "name": ["Rahul","Ravi"],
    "skills": ["Python", "SQL", "Excel"],
    "experience": [3,4],
    "city": ["Chennai","Bangalore"]}

employees_team_B = employees_team_A.copy()
employees_team_B

{'emp_id': [101, 102],
 'name': ['Rahul', 'Ravi'],
 'skills': ['Python', 'SQL', 'Excel'],
 'experience': [3, 4],
 'city': ['Chennai', 'Bangalore']}

In [78]:
employees_team_A = {
    "emp_id": [101,102],
    "name": ["Rahul","Ravi"],
    "skills": ["Python", "SQL", "Excel"],
    "experience": [3,4],
    "city": ["Chennai","Bangalore"]}
employees_team_A.clear()
employees_team_A

{}