# 1.	Write a program to take a name and age from the user and print a greeting message.

In [2]:
name = input("Please enter your name:")
age = int(input("please enter your age:"))
print("Welcome {} to proitbridge at the age of {}".format(name,age))

Please enter your name: Vasu
please enter your age: 28

Welcome Vasu to proitbridge at the age of 28

# 2.	Create a list of numbers and print only even numbers using a for loop.

In [4]:
numbers = [2,3,4,5,6,7,8,9,10]
even_numbers = []
for i in numbers:
    if i % 2 == 0:
        even_numbers.append(i)
even_numbers

[2, 4, 6, 8, 10]

# 3.	Write a program that handles division by zero using try-except.

In [11]:
numbers = 2,3,0,4
odd_numbers = []
for i in numbers:
    try:
        if i % 0:
            print(f"{i} divided by 0",i)
    except:
        print("Loop failed because of i % 0")

Loop failed because of i % 0
Loop failed because of i % 0
Loop failed because of i % 0
Loop failed because of i % 0

# 4.	Given a string, count how many vowels it has

In [34]:
user_input = input("Enter the word to found the number of vowels:")
vowels = "a","e","i","o","u"
for i in user_input:
    if i in vowels:
        print(i)

Enter the word to found the number of vowels: vasu

a
u

# 5.	Reverse a list without using built-in functions.

In [46]:
user_list = [2,3,4,5,6]
reverse_list = []
for i in range(4,-1,-1):
    reverse_list.append(i)
    print(i)
reverse_list

4
3
2
1
0

[4, 3, 2, 1, 0]

# 6.	Create a dictionary with at least 5 key-value pairs and print them.

In [48]:
student_detail = {"name" :["Ajay","Vijay"],
                  "Class" : ["A","B"],
                  "Math" : [75,80],
                  "Science" : [86,87],
                  "History" : [92,93]}
student_detail

{'name': ['Ajay', 'Vijay'],
 'Class': ['A', 'B'],
 'Math': [75, 80],
 'Science': [86, 87],
 'History': [92, 93]}

# 7.	Write a Pandas code to read a CSV and print the top 5 rows.

In [50]:
import pandas as pd
employee_details = pd.read_csv("Employee_Data.csv")
employee_details.head()

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024

# 8.	Create a DataFrame from a Python dictionary.

In [54]:
student_detail = {"name" :["Ajay","Vijay"],
                  "Class" : ["A","B"],
                  "Math" : [75,80],
                  "Science" : [86,87],
                  "History" : [92,93]}
student_Dataframe = pd.DataFrame(student_detail)
student_Dataframe

    name Class  Math  Science  History
0   Ajay     A    75       86       92
1  Vijay     B    80       87       93

# 9.	Replace all missing values in a DataFrame with the column’s mean.

In [56]:
import pandas as pd
employee_details = pd.read_csv("Employee_Data.csv")
employee_details

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [57]:
employee_details.describe()

             Age        Salary
count   7.000000      6.000000
mean   31.857143  62500.000000
std     4.259443   5049.752469
min    28.000000  58000.000000
25%    29.000000  60000.000000
50%    31.000000  60500.000000
75%    33.000000  63250.000000
max    40.000000  72000.000000

# 10.	Filter rows in a DataFrame where the "Age" column is greater than 30.

In [58]:
employee_details[employee_details["Age"] > 30]

    Name   Age Department   Salary   Join_Date
1  Nasir  31.0    IT Tech      NaN  12-11-2020
5  Navin  35.0    Support  72000.0  19-08-2023
6    NaN  40.0         IT  64000.0  10-09-2022
7  Nasir  31.0    IT Tech      NaN  12-11-2020