#   1. Find and Fix Missing Values
    2. Remove Duplicates
    3. Fix data type(convert to int/float from str/object)

In [455]:
import pandas as pd
sales_data_2017 = pd.read_csv("Sales_Transactions_2017.csv")
sales_data_2017

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137,"3,425.00",NaN,"3,425.00"
47286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47288,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13"
47289,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71"

In [456]:
sales_data_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47290 entries, 0 to 47289
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            41902 non-null  object
 1   Voucher         41915 non-null  object
 2   Party           47275 non-null  object
 3   Product         41902 non-null  object
 4   Qty             41915 non-null  object
 5   Rate            41914 non-null  object
 6   Gross           41914 non-null  object
 7   Disc            2858 non-null   object
 8   Voucher Amount  11348 non-null  object
dtypes: object(9)
memory usage: 3.2+ MB

In [457]:
sales_data_2017.isna().sum()

Date               5388
Voucher            5375
Party                15
Product            5388
Qty                5375
Rate               5376
Gross              5376
Disc              44432
Voucher Amount    35942
dtype: int64

In [458]:
sales_data_2017.describe(include="all")

         Date Voucher  Party Product    Qty   Rate  Gross  Disc Voucher Amount
count   41902   41915  47275   41902  41915  41914  41914  2858          11348
unique    330    9993   1114     616    302    721   1547   201           4056
top                     TP13            100     26
freq     1345    1345   5663    1345   5860   2194   1345  1345           1345

In [459]:
sales_data_2017.duplicated().sum()

np.int64(6205)

# Finding rows with summary

In [460]:
sales_data_2017[sales_data_2017["Voucher"] == "Total"]

Empty DataFrame
Columns: [Date, Voucher, Party, Product, Qty, Rate, Gross, Disc, Voucher Amount]
Index: []

In [461]:
sales_data_2017[sales_data_2017['Voucher'].astype(str).str.contains('Total', case=False, na=False)]

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
4286,NaN,Total,NaN,NaN,"725,098.20","892,995.90","10,156,375.86","99,183.00","10,079,469.86"
9440,NaN,Total,NaN,NaN,"864,048.00","842,990.34","11,738,640.00","76,449.00","11,690,343.00"
13637,NaN,Total,NaN,NaN,"742,449.00","639,799.63","9,994,892.00","115,371.00","9,905,775.00"
17195,NaN,Total,NaN,NaN,"569,166.00","684,525.17","9,196,270.50","68,314.00","9,147,636.50"
21653,NaN,Total,NaN,NaN,"800,911.60","916,383.98","11,487,277.00","80,427.00","11,434,171.00"
25642,NaN,Total,NaN,NaN,"616,175.60","654,104.12","9,814,351.46","88,940.00","9,749,457.46"
29365,NaN,Total,NaN,NaN,"638,342.70","621,104.41","9,496,760.91","65,056.00","9,453,182.91"
33121,NaN,Total,NaN,NaN,"551,198.00","643,446.58","9,132,584.78","52,087.00","9,100,067.78"
37214,NaN,Total,NaN,NaN,"538,900.90","728,887.38","9,390,510.25","82,913.00","9,326,772.25"
40415,NaN,Total,NaN,NaN,"458,230.80","554,312.00","7,844,514.06","49,961.00","7,811,481.06"
43289,NaN,Total,NaN,NaN,"480,806.30","461,266.00","7,572,732.76","51,040.00","7,538,183.76"
47288,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13"
47289,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71"

In [462]:
rows_with_total = sales_data_2017[sales_data_2017["Voucher"].astype(str).str.contains("Total",case=False,na=False)]

In [463]:
rows_with_total.shape

(13, 9)

In [464]:
sales_data_2017 = sales_data_2017.drop(rows_with_total.index)

In [465]:
sales_data_2017.shape

(47277, 9)

In [466]:
sales_data_2017[sales_data_2017["Voucher"].astype(str).str.contains("Total",case=False,na=False)]

Empty DataFrame
Columns: [Date, Voucher, Party, Product, Qty, Rate, Gross, Disc, Voucher Amount]
Index: []

# Check Missing values again

In [467]:
sales_data_2017.isna().sum()

Date               5375
Voucher            5375
Party                 2
Product            5375
Qty                5375
Rate               5376
Gross              5376
Disc              44432
Voucher Amount    35942
dtype: int64

In [468]:
sales_data_2017[sales_data_2017["Date"].isna()].head(10)

   Date Voucher            Party Product  Qty Rate Gross Disc Voucher Amount
11  NaN     NaN           #NAME?     NaN  NaN  NaN   NaN  NaN            NaN
14  NaN     NaN           #NAME?     NaN  NaN  NaN   NaN  NaN            NaN
39  NaN     NaN           #NAME?     NaN  NaN  NaN   NaN  NaN            NaN
41  NaN     NaN           #NAME?     NaN  NaN  NaN   NaN  NaN            NaN
43  NaN     NaN           #NAME?     NaN  NaN  NaN   NaN  NaN            NaN
53  NaN     NaN               KR     NaN  NaN  NaN   NaN  NaN            NaN
55  NaN     NaN               KR     NaN  NaN  NaN   NaN  NaN            NaN
77  NaN     NaN        IC CENTRE     NaN  NaN  NaN   NaN  NaN            NaN
79  NaN     NaN  LAKSHMIMEDICALS     NaN  NaN  NaN   NaN  NaN            NaN
81  NaN     NaN  LAKSHMIMEDICALS     NaN  NaN  NaN   NaN  NaN            NaN

In [469]:
sales_data_2017[sales_data_2017["Date"].isna()].isna().sum()

Date              5375
Voucher           5375
Party                2
Product           5375
Qty               5375
Rate              5375
Gross             5375
Disc              5375
Voucher Amount    5375
dtype: int64

## Find if any of the row has value in Date column using notna()

In [470]:
sales_data_2017[sales_data_2017["Date"].isna()].notna().sum()

Date                 0
Voucher              0
Party             5373
Product              0
Qty                  0
Rate                 0
Gross                0
Disc                 0
Voucher Amount       0
dtype: int64

##  Remove rows where Date is missing and replace dataframe with only rows which value in Date column(valid transaction should have date)

In [471]:
sales_data_2017 = sales_data_2017[sales_data_2017["Date"].notna()]

In [472]:
sales_data_2017.shape

(41902, 9)

In [473]:
sales_data_2017.isna().sum()

Date                  0
Voucher               0
Party                 0
Product               0
Qty                   0
Rate                  1
Gross                 1
Disc              39057
Voucher Amount    30567
dtype: int64

## Rate column has one missing value. so check whther that can be fill out or not

In [474]:
sales_data_2017[sales_data_2017["Rate"].isna()]

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
43740,5/3/2018,Sal:9266,CUSTOMER,TIRML-BL-KG-17*23,2,NaN,NaN,NaN,NaN

## check the rate for this product

In [475]:
sales_data_2017[sales_data_2017["Product"] == "TIRML-BL-KG-17*23"][["Date", "Product", "Qty", "Rate", "Gross"]]

             Date            Product Qty Rate     Gross
425      5/4/2017  TIRML-BL-KG-17*23  10  110  1,100.00
627      6/4/2017  TIRML-BL-KG-17*23  25  120  3,000.00
762      7/4/2017  TIRML-BL-KG-17*23   6  120       720
1294    11/4/2017  TIRML-BL-KG-17*23   1  130       130
1462    12/4/2017  TIRML-BL-KG-17*23  10  125  1,250.00
...           ...                ...  ..  ...       ...
44778  13/03/2018  TIRML-BL-KG-17*23   5  130       650
44857  14/03/2018  TIRML-BL-KG-17*23   2  130       260
45254  17/03/2018  TIRML-BL-KG-17*23  10  120  1,200.00
46380  27/03/2018  TIRML-BL-KG-17*23  10  130  1,300.00
47057  31/03/2018  TIRML-BL-KG-17*23  25  125  3,125.00

[108 rows x 5 columns]

In [476]:
sales_data_2017[sales_data_2017["Product"] == "TIRML-BL-KG-17*23"]["Qty"].value_counts()

Qty
25    36
5     24
10    13
3     13
2      8
6      6
1      5
9      1
4      1
50     1
Name: count, dtype: int64

In [477]:
sales_data_2017[sales_data_2017["Product"] == "TIRML-BL-KG-17*23"]["Rate"].value_counts()

Rate
125    38
130    32
120    24
115     8
110     5
Name: count, dtype: int64

## Since Rate is changing over the days and it is affecting only one row lets document the decision as below and delete the row

## Removed the single transaction with missing Rate and other critical transaction values because the missing values could not be reliably inferred.

In [478]:
sales_data_2017.loc[43740]

Date                       5/3/2018
Voucher                    Sal:9266
Party                      CUSTOMER
Product           TIRML-BL-KG-17*23
Qty                               2
Rate                            NaN
Gross                           NaN
Disc                            NaN
Voucher Amount                  NaN
Name: 43740, dtype: object

In [479]:
sales_data_2017 = sales_data_2017.drop(43740)

In [480]:
sales_data_2017.isna().sum()

Date                  0
Voucher               0
Party                 0
Product               0
Qty                   0
Rate                  0
Gross                 0
Disc              39056
Voucher Amount    30566
dtype: int64

In [481]:
sales_data_2017.loc(43740)

ValueError: No axis named 43740 for object type DataFrame

In [ ]:
sales_data_2017

In [ ]:
sales_data_2017_cleaned = sales_data_2017[["Date","Voucher","Party","Product","Qty","Rate"]]

In [ ]:
sales_data_2017_cleaned.head(5)

In [ ]:
sales_data_2017_cleaned.shape

In [ ]:
sales_data_2017_cleaned.isna().sum()

# 2. No duplicates found in this dataset

In [ ]:
sales_data_2017_cleaned.duplicated().sum()

# 3. Fix Data types

In [ ]:
sales_data_2017_cleaned.dtypes

## Qty and Rate should be integer. Lets fix. quantity may values like "2 PCS","-","NA","100".

In [ ]:
sales_data_2017_cleaned["Qty"].unique()

In [ ]:
sales_data_2017_cleaned[sales_data_2017_cleaned["Qty"] == " "]

In [ ]:
(sales_data_2017_cleaned["Qty"]==" ").sum()

In [ ]:
## remove rows with qty ==" " because other columns also dont have values

In [ ]:
sales_data_2017_cleaned = sales_data_2017_cleaned[sales_data_2017_cleaned["Qty"] != " "]

In [ ]:
sales_data_2017_cleaned.shape

In [ ]:
sales_data_2017_cleaned["Qty"].str.contains(",",na=False).sum()

In [ ]:
sales_data_2017_cleaned["Qty"] = sales_data_2017_cleaned["Qty"].str.replace(",","")

In [ ]:
sales_data_2017_cleaned = sales_data_2017[["Date", "Voucher", "Party", "Product", "Qty", "Rate"]].copy()

In [ ]:
sales_data_2017_cleaned.shape

In [ ]:
(sales_data_2017_cleaned["Qty"].str.contains(" ",na=False)).sum()

In [ ]:
type(sales_data_2017_cleaned)

In [ ]:
sales_data_2017_cleaned.columns

In [ ]:
sales_data_2017_cleaned = sales_data_2017[["Date", "Voucher", "Party", "Product", "Qty", "Rate"]].copy()

In [ ]:
type(sales_data_2017_cleaned)

In [ ]:
sales_data_2017_cleaned.columns

In [ ]:
sales_data_2017_cleaned["Qty"].str.contains(" ",na=False).sum()

In [ ]:
(sales_data_2017_cleaned["Qty"] == " ").sum()

In [ ]:
sales_data_2017_cleaned = sales_data_2017_cleaned[sales_data_2017_cleaned["Qty"] != " "].copy()

In [ ]:
sales_data_2017_cleaned.shape

In [ ]:
sales_data_2017_cleaned.columns

In [ ]:
type(sales_data_2017_cleaned)

In [ ]:
(sales_data_2017_cleaned["Qty"].str.contains(",",na=False)).sum()

In [ ]:
sales_data_2017_cleaned["Qty"] = sales_data_2017_cleaned["Qty"].str.replace(",", "", regex=False)

In [ ]:
(sales_data_2017_cleaned["Qty"].str.contains(",",na=False)).sum()

In [ ]:
sales_data_2017_cleaned["Qty"] = pd.to_numeric(sales_data_2017_cleaned["Qty"])

In [ ]:
sales_data_2017_cleaned["Qty"].dtype

In [ ]:
sales_data_2017_cleaned.dtypes

In [ ]:
sales_data_2017_cleaned["Qty"].unique()

In [ ]:
sales_data_2017_cleaned["Rate"].unique()

In [ ]:
(sales_data_2017_cleaned["Rate"].str.contains(",", na=False)).sum()

In [ ]:
sales_data_2017_cleaned["Rate"]=sales_data_2017_cleaned["Rate"].str.replace(",","")

In [ ]:
(sales_data_2017_cleaned["Rate"].str.contains(",", na=False)).sum()

In [ ]:
sales_data_2017_cleaned["Rate"]=pd.to_numeric(sales_data_2017_cleaned["Rate"])

In [ ]:
sales_data_2017_cleaned["Rate"].dtype

In [ ]:
sales_data_2017_cleaned["Rate"].isnull().sum()

In [ ]:
sales_data_2017_cleaned.dtypes

## convert Date column

In [ ]:
sales_data_2017_cleaned["Date"].unique()[:20]

In [ ]:
sales_data_2017_cleaned["Date"].isna().sum()

In [ ]:
sales_data_2017_cleaned["Date"] = pd.to_datetime(sales_data_2017_cleaned["Date"],dayfirst= True)

In [ ]:
sales_data_2017_cleaned["Date"].dtype

In [ ]:
sales_data_2017_cleaned.dtypes

In [ ]:
sales_data_2017_cleaned["Date"].isna().sum()

# Check duplicate rows in dataframe

In [ ]:
sales_data_2017_cleaned.duplicated().sum()

In [ ]:
sales_data_2017_cleaned[sales_data_2017_cleaned.duplicated(keep=False)].head(20)

In [ ]:
sales_data_2017_cleaned[sales_data_2017_cleaned.duplicated(keep=False)]["Voucher"].value_counts()

In [ ]:
sales_data_2017_cleaned[sales_data_2017_cleaned["Voucher"] == "Sal:1506"]

In [ ]:
sales_data_2017_cleaned[sales_data_2017_cleaned.duplicated(keep=False)].value_counts()

In [ ]:
sales_data_2017_cleaned = sales_data_2017_cleaned.drop_duplicates() #drop duplicates

In [ ]:
sales_data_2017_cleaned.duplicated().sum()

In [ ]:
sales_data_2017_cleaned.shape

# Check invalid values

In [ ]:
sales_data_2017_cleaned["Date"].isna().sum()

In [ ]:
sales_data_2017_cleaned["Date"].min()

In [ ]:
sales_data_2017_cleaned["Date"].max()

In [ ]:
sales_data_2017_cleaned["Voucher"].isna().sum()

In [ ]:
sales_data_2017_cleaned["Voucher"].str.strip().eq("").sum()

In [ ]:
sales_data_2017_cleaned["Party"].isna().sum()

In [ ]:
sales_data_2017_cleaned["Party"].str.strip().eq("").sum()

In [ ]:
sales_data_2017_cleaned["Product"].isna().sum()

In [ ]:
sales_data_2017_cleaned["Product"].str.strip().eq("").sum()

In [ ]:
sales_data_2017_cleaned["Qty"].isna().sum()

In [ ]:
sales_data_2017_cleaned[sales_data_2017_cleaned["Qty"] <= 0]

In [ ]:
sales_data_2017_cleaned["Rate"].isna().sum()

In [ ]:
sales_data_2017_cleaned[sales_data_2017_cleaned["Rate"] <= 0]

In [ ]:
sales_data_2017_cleaned.info()

In [ ]:
sales_data_2017_cleaned = sales_data_2017_cleaned.reset_index(drop=True)

In [ ]:
sales_data_2017_cleaned.info()

# Cleaning Sales_Transactions_2018

In [ ]:
import pandas as pd

In [ ]:
sales_data_2018_cleaned = pd.read_csv("Sales_Transactions_2018.csv")

In [ ]:
sales_data_2018_cleaned.shape

In [ ]:
sales_data_2018_cleaned.info()

In [ ]:
sales_data_2018_cleaned = sales_data_2018_cleaned[["Date","Voucher","Party","Product","Qty","Rate"]].copy()

In [ ]:
sales_data_2018_cleaned.info()

## Missing value check

In [ ]:
sales_data_2018_cleaned.isna().sum()

In [ ]:
sales_data_2018_cleaned[sales_data_2018_cleaned["Date"].isna()]

In [ ]:
sales_data_2018_cleaned[sales_data_2018_cleaned["Date"].isna()].notna().sum()

In [ ]:
sales_data_2018_cleaned[sales_data_2018_cleaned["Date"].isna() & sales_data_2018_cleaned["Voucher"].notna()]

In [ ]:
sales_data_2018_cleaned[sales_data_2018_cleaned["Date"].isna()].head(20)

In [ ]:
sales_data_2018_cleaned[sales_data_2018_cleaned["Date"].isna()].notna().sum(axis=1).value_counts()

In [ ]:
sales_data_2018_cleaned = sales_data_2018_cleaned[sales_data_2018_cleaned["Date"].notna()].copy()

In [ ]:
sales_data_2018_cleaned.shape

In [ ]:
sales_data_2018_cleaned[sales_data_2018_cleaned["Party"].isna()]

In [ ]:
sales_data_2018_cleaned.isna().sum()

## Blank/space value check

In [ ]:
sales_data_2018_cleaned["Voucher"].str.strip().eq("").sum()

In [ ]:
sales_data_2018_cleaned[sales_data_2018_cleaned["Voucher"].str.strip().eq("")].head(20)

In [ ]:
sales_data_2018_cleaned[sales_data_2018_cleaned["Voucher"].str.strip().eq("")].notna().sum(axis=1).value_counts()

In [ ]:
sales_data_2018_cleaned[sales_data_2018_cleaned["Voucher"].str.strip().eq("")].iloc[0]

In [ ]:
sales_data_2018_cleaned[sales_data_2018_cleaned["Voucher"].str.strip() == ""].head(10)

In [ ]:
sales_data_2018_cleaned = sales_data_2018_cleaned[sales_data_2018_cleaned["Voucher"].str.strip() != ""].copy()

In [ ]:
sales_data_2018_cleaned.shape

In [ ]:
sales_data_2018_cleaned["Party"].str.strip().eq("").sum()

In [ ]:
sales_data_2018_cleaned["Product"].str.strip().eq("").sum()

In [ ]:
sales_data_2018_cleaned["Qty"].isna().sum()

In [ ]:
sales_data_2018_cleaned["Qty"].str.strip().eq("").sum()

In [ ]:
sales_data_2018_cleaned["Qty"].str.contains(",", na=False).sum()

In [ ]:
sales_data_2018_cleaned["Qty"] = sales_data_2018_cleaned["Qty"].str.replace(",", "")

In [ ]:
sales_data_2018_cleaned["Qty"].str.contains(",").sum()

In [ ]:
sales_data_2018_cleaned["Qty"] = pd.to_numeric(sales_data_2018_cleaned["Qty"])

In [ ]:
sales_data_2018_cleaned.dtypes

In [ ]:
sales_data_2018_cleaned["Rate"].isna().sum()

In [ ]:
sales_data_2018_cleaned["Rate"].str.strip().eq("").sum()

In [ ]:
sales_data_2018_cleaned["Rate"].str.contains(",").sum()

In [ ]:
sales_data_2018_cleaned["Rate"] = sales_data_2018_cleaned["Rate"].str.replace(",", "")

In [ ]:
sales_data_2018_cleaned["Rate"].str.contains(",").sum()

In [ ]:
sales_data_2018_cleaned["Rate"] = pd.to_numeric(sales_data_2018_cleaned["Rate"])

In [ ]:
sales_data_2018_cleaned.dtypes

In [ ]:
sales_data_2018_cleaned["Date"].head(10)

In [ ]:
sales_data_2018_cleaned["Date"] = pd.to_datetime(sales_data_2018_cleaned["Date"],dayfirst=True)

In [ ]:
sales_data_2018_cleaned.dtypes

# Investigate duplicate values

In [ ]:
sales_data_2018_cleaned.duplicated().sum()

In [ ]:
sales_data_2018_cleaned[sales_data_2018_cleaned.duplicated(keep=False)]

In [ ]:
sales_data_2018_cleaned[sales_data_2018_cleaned.duplicated(keep=False)].value_counts()

In [ ]:
sales_data_2018_cleaned = sales_data_2018_cleaned.drop_duplicates()

In [ ]:
sales_data_2018_cleaned.shape

In [ ]:
sales_data_2018_cleaned.duplicated().sum()

# Negative and zero value check for numeric columns

In [ ]:
sales_data_2018_cleaned[sales_data_2018_cleaned["Qty"] <= 0]

In [ ]:
sales_data_2018_cleaned[sales_data_2018_cleaned["Rate"] <= 0]

In [ ]:
sales_data_2018_cleaned["Date"].min()

In [ ]:
sales_data_2018_cleaned["Date"].max()

In [ ]:
sales_data_2018_cleaned.info()

# Cleaning Sales_Transactions_2019

In [ ]:
import pandas as pd

In [ ]:
sales_data_2019_cleaned = pd.read_csv("Sales_Transactions_2019.csv")

In [ ]:
sales_data_2019_cleaned.shape

In [ ]:
sales_data_2019_cleaned.info()

In [ ]:
sales_data_2019_cleaned = sales_data_2019_cleaned[["Date","Voucher","Party","Product","Qty","Rate"]].copy()

In [ ]:
sales_data_2019_cleaned.info()

## Missing Value Analysis(NaN)

In [ ]:
sales_data_2019_cleaned[sales_data_2019_cleaned["Date"].isna()].head(20)

In [ ]:
sales_data_2019_cleaned[sales_data_2019_cleaned["Date"].isna()].notna().sum()

In [ ]:
sales_data_2019_cleaned[sales_data_2019_cleaned["Date"].isna() &sales_data_2019_cleaned["Voucher"].notna()]

In [ ]:
sales_data_2019_cleaned = sales_data_2019_cleaned.dropna(subset=["Date"])

In [ ]:
sales_data_2019_cleaned.shape

In [ ]:
sales_data_2019_cleaned.isna().sum()

In [ ]:
## Blank Space check

In [ ]:
sales_data_2019_cleaned["Date"].str.strip().eq("").sum()

In [ ]:
sales_data_2019_cleaned[sales_data_2019_cleaned["Date"].str.strip() == ""].head(20)

In [ ]:
sales_data_2019_cleaned[sales_data_2019_cleaned["Date"].str.strip() == ""].notna().sum()

In [ ]:
sales_data_2019_cleaned[sales_data_2019_cleaned["Date"].str.strip() == ""]["Voucher"].str.strip().eq("").sum()

In [ ]:
sales_data_2019_cleaned[sales_data_2019_cleaned["Date"].str.strip() == ""]["Party"].str.strip().eq("").sum()

In [ ]:
sales_data_2019_cleaned[sales_data_2019_cleaned["Date"].str.strip() == ""]["Product"].str.strip().eq("").sum()

In [ ]:
sales_data_2019_cleaned[sales_data_2019_cleaned["Date"].str.strip() == ""]["Qty"].str.strip().eq("").sum()

In [ ]:
sales_data_2019_cleaned[(sales_data_2019_cleaned["Date"].str.strip() == "") &(sales_data_2019_cleaned["Qty"].str.strip() != "")]

In [ ]:
sales_data_2019_cleaned[sales_data_2019_cleaned["Date"].str.strip() == ""]["Rate"].str.strip().eq("").sum()

In [ ]:
sales_data_2019_cleaned = sales_data_2019_cleaned[sales_data_2019_cleaned["Date"].str.strip() != ""].copy()

In [ ]:
sales_data_2019_cleaned.shape

In [ ]:
sales_data_2019_cleaned["Voucher"].str.strip().eq("").sum()

In [ ]:
sales_data_2019_cleaned["Voucher"].isna().sum()

In [ ]:
sales_data_2019_cleaned["Party"].isna().sum() # NaN check

In [ ]:
sales_data_2019_cleaned["Party"].str.strip().eq("").sum() # blank space check

In [ ]:
sales_data_2019_cleaned["Product"].isna().sum()

In [ ]:
sales_data_2019_cleaned["Product"].str.strip().eq("").sum()

In [ ]:
sales_data_2019_cleaned["Qty"].isna().sum()

In [ ]:
sales_data_2019_cleaned["Qty"].str.strip().eq("").sum()

In [ ]:
sales_data_2019_cleaned["Rate"].isna().sum()

In [ ]:
sales_data_2019_cleaned["Rate"].str.strip().eq("").sum()

In [ ]:
## type cleaning the column

In [ ]:
sales_data_2019_cleaned["Qty"].str.contains(",").sum()

In [ ]:
sales_data_2019_cleaned["Qty"]=sales_data_2019_cleaned["Qty"].str.replace(",","")

In [ ]:
sales_data_2019_cleaned["Qty"].str.contains(",").sum()

In [ ]:
sales_data_2019_cleaned["Rate"].str.contains(",").sum()

In [ ]:
sales_data_2019_cleaned["Rate"]=sales_data_2019_cleaned["Rate"].str.replace(",","")

In [ ]:
sales_data_2019_cleaned["Rate"].str.contains(",").sum()

In [ ]:
sales_data_2019_cleaned["Qty"]=pd.to_numeric(sales_data_2019_cleaned["Qty"])

In [ ]:
sales_data_2019_cleaned.dtypes

In [ ]:
sales_data_2019_cleaned["Rate"]=pd.to_numeric(sales_data_2019_cleaned["Rate"])

In [ ]:
sales_data_2019_cleaned.dtypes

In [ ]:
sales_data_2019_cleaned["Date"]=pd.to_datetime(sales_data_2019_cleaned["Date"],dayfirst=True)

In [ ]:
sales_data_2019_cleaned.dtypes

# Duplicate check

In [ ]:
sales_data_2019_cleaned.duplicated().sum()

In [ ]:
sales_data_2019_cleaned[sales_data_2019_cleaned.duplicated(keep=False)]

In [ ]:
sales_data_2019_cleaned = sales_data_2019_cleaned.drop_duplicates()

In [ ]:
sales_data_2019_cleaned.duplicated().sum()

In [ ]:
# Negative/zero value check in numeric column

In [ ]:
sales_data_2019_cleaned[sales_data_2019_cleaned["Qty"] <= 0]

In [ ]:
sales_data_2019_cleaned[sales_data_2019_cleaned["Rate"] <=0]

In [ ]:
sales_data_2019_cleaned.info()

# Combine all 3 dataframes

In [484]:
sales_data_2017_cleaned.columns

Index(['Date', 'Voucher', 'Party', 'Product', 'Qty', 'Rate'], dtype='object')

In [482]:
sales_data_2018_cleaned.columns

Index(['Date', 'Voucher', 'Party', 'Product', 'Qty', 'Rate'], dtype='object')

In [483]:
sales_data_2019_cleaned.columns

Index(['Date', 'Voucher', 'Party', 'Product', 'Qty', 'Rate'], dtype='object')

In [485]:
sales_data_2017_cleaned.dtypes

Date       datetime64[ns]
Voucher            object
Party              object
Product            object
Qty               float64
Rate              float64
dtype: object

In [486]:
sales_data_2018_cleaned.dtypes

Date       datetime64[ns]
Voucher            object
Party              object
Product            object
Qty               float64
Rate              float64
dtype: object

In [487]:
sales_data_2019_cleaned.dtypes

Date       datetime64[ns]
Voucher            object
Party              object
Product            object
Qty               float64
Rate              float64
dtype: object

In [488]:
sales_data_combined = pd.concat([sales_data_2017_cleaned, sales_data_2018_cleaned, sales_data_2019_cleaned],ignore_index=True)

In [489]:
sales_data_combined.shape

(95223, 6)

In [490]:
sales_data_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95223 entries, 0 to 95222
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     95223 non-null  datetime64[ns]
 1   Voucher  95223 non-null  object
 2   Party    95223 non-null  object
 3   Product  95223 non-null  object
 4   Qty      95223 non-null  float64
 5   Rate     95223 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 4.4+ MB

In [491]:
sales_data_combined.duplicated().sum()

np.int64(0)

In [492]:
sales_data_combined[sales_data_combined["Qty"] <= 0]

Empty DataFrame
Columns: [Date, Voucher, Party, Product, Qty, Rate]
Index: []

In [493]:
sales_data_combined[sales_data_combined["Rate"] <= 0]

Empty DataFrame
Columns: [Date, Voucher, Party, Product, Qty, Rate]
Index: []

In [494]:
sales_data_combined["Date"].min()

Timestamp('2017-04-01 00:00:00')

In [495]:
sales_data_combined["Date"].max()

Timestamp('2019-10-10 00:00:00')