# Task 2. Merge Function 1 Example

In [6]:
import pandas as pd

customer_details = pd.DataFrame({
    "customer_id": [101, 102, 103, 104],
    "name": ["Ravi", "Priya", "Akil", "Anu"]})
customer_details

   customer_id   name
0          101   Ravi
1          102  Priya
2          103   Akil
3          104    Anu

In [7]:
order_details = pd.DataFrame({
    "customer_id": [101, 102, 101, 105],
    "product": ["Laptop", "Phone", "Mouse", "Keyboard"],
    "amount": [50000, 20000, 1000, 3000]})
order_details

   customer_id   product  amount
0          101    Laptop   50000
1          102     Phone   20000
2          101     Mouse    1000
3          105  Keyboard    3000

## Inner Merge

In [14]:
inner_merge = pd.merge(customer_details,order_details,on="customer_id",how="inner")
inner_merge

   customer_id   name product  amount
0          101   Ravi  Laptop   50000
1          101   Ravi   Mouse    1000
2          102  Priya   Phone   20000

In [11]:
pd.merge(customer_details,order_details,on="customer_id")

   customer_id   name product  amount
0          101   Ravi  Laptop   50000
1          101   Ravi   Mouse    1000
2          102  Priya   Phone   20000

## Left Merge

In [16]:
Left_merge = pd.merge(customer_details,order_details,on="customer_id",how="left")
Left_merge

   customer_id   name product   amount
0          101   Ravi  Laptop  50000.0
1          101   Ravi   Mouse   1000.0
2          102  Priya   Phone  20000.0
3          103   Akil     NaN      NaN
4          104    Anu     NaN      NaN

## Right Merge

In [19]:
Right_merge = pd.merge(customer_details,order_details,on="customer_id",how="right")
Right_merge

   customer_id   name   product  amount
0          101   Ravi    Laptop   50000
1          102  Priya     Phone   20000
2          101   Ravi     Mouse    1000
3          105    NaN  Keyboard    3000

## Outer Merge

In [20]:
outer_merge = pd.merge(customer_details,order_details,on="customer_id",how="outer")
outer_merge

   customer_id   name   product   amount
0          101   Ravi    Laptop  50000.0
1          101   Ravi     Mouse   1000.0
2          102  Priya     Phone  20000.0
3          103   Akil       NaN      NaN
4          104    Anu       NaN      NaN
5          105    NaN  Keyboard   3000.0

## Cross Merge - Every possible combination

In [21]:
cross_merge = pd.merge(customer_details,order_details,how="cross")
cross_merge

    customer_id_x   name  customer_id_y   product  amount
0             101   Ravi            101    Laptop   50000
1             101   Ravi            102     Phone   20000
2             101   Ravi            101     Mouse    1000
3             101   Ravi            105  Keyboard    3000
4             102  Priya            101    Laptop   50000
5             102  Priya            102     Phone   20000
6             102  Priya            101     Mouse    1000
7             102  Priya            105  Keyboard    3000
8             103   Akil            101    Laptop   50000
9             103   Akil            102     Phone   20000
10            103   Akil            101     Mouse    1000
11            103   Akil            105  Keyboard    3000
12            104    Anu            101    Laptop   50000
13            104    Anu            102     Phone   20000
14            104    Anu            101     Mouse    1000
15            104    Anu            105  Keyboard    3000

# Task 3. List Comprehension

# 1. Create a new list containing each number multiplied by 5

In [25]:
numbers = [2, 4, 6, 8, 10]
new_numbers =[i * 5 for i in numbers]
new_numbers

[10, 20, 30, 40, 50]

# 2. Create a new list containing only the numbers greater than 10

In [31]:
numbers = [2, 5, 8, 11, 14, 17, 20]
new_list = [i for i in numbers if i > 10]
new_list

[11, 14, 17, 20]

# 3. Create a new list that contains the square of only the numbers greater than 10.

In [32]:
numbers = [2, 5, 8, 11, 14, 17, 20]
new_list = [ i * i for i in numbers if i > 10]
new_list

[121, 196, 289, 400]

# 4. Create a new list where: If the number is even, put "Even" Otherwise, put "Odd"

In [34]:
numbers = [1, 2, 3, 4, 5, 6]
new_list = [ "Even" if i %2 ==0  else "Odd" for i in numbers]
new_list

['Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even']

In [35]:
ages = [15, 22, 17, 35, 12, 28, 16, 40]
new_list =["Adult" if i > 18 else "Minor" for i in ages]
new_list

['Minor', 'Adult', 'Minor', 'Adult', 'Minor', 'Adult', 'Minor', 'Adult']

# Task 4: Lambda with Map,Filter,Reduce

In [51]:
numbers = [1, 2, 3, 4, 5]
square = list(map(lambda x: x * x, numbers))
square

[1, 4, 9, 16, 25]

## 1. create a new list where every number is multiplied by 3.

In [53]:
numbers = [2, 4, 6, 8, 10]
new_list = list(map(lambda x: x * 3 , numbers))
new_list

[6, 12, 18, 24, 30]

## 2. Convert all names to uppercase.

In [57]:
names = ["ravi", "priya", "akil", "anu"]
upper_case_names = list(map(lambda x: x.upper(),names))
upper_case_names

['RAVI', 'PRIYA', 'AKIL', 'ANU']

## 3. keep only numbers greater than 15.

In [61]:
numbers = [5, 10, 15, 20, 25, 30]
new_numbers = list(filter(lambda x: x > 15,numbers))
new_numbers

[20, 25, 30]

## 4. keep only adults (age 18 and above)

In [62]:
ages = [12, 18, 25, 16, 30, 15, 21]
new_list = list(filter(lambda x: x > 18,ages))
new_list

[25, 30, 21]

## 5. calculate the sum of all numbers.

In [72]:
from functools import reduce
numbers = [2, 4, 6, 8]
total = reduce(lambda x,y: x + y,numbers)
total

20

## 6. calculate the multiplication of all numbers.

In [74]:
numbers = [2, 3, 4, 5]
product = reduce(lambda x,y: x*y,numbers)
product

120